version: '3'
services:
  frontend:
    image: acrcouldresgistry.azurecr.io/flamesunrise/lab1_frontend:v1
    ports:
      - 3000
    environment:
      - API_HOST=backend
      - API_PORT=8080
    networks:
      - my-network
  backend:
    image: acrcouldresgistry.azurecr.io/flamesunrise/lab1_backend:v1
    environment:
      - API_HOST=backend
      - API_PORT=8080
    depends_on:
      - database
    networks:
      - my-network
  database:
    image: acrcouldresgistry.azurecr.io/flamesunrise/lab1_database:v1
    hostname: my-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=Test
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
