name: DockerHub Lab1-ToDOList Deploy to Azure Web App

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches: [ main ]

env:
  AZURE_WEBAPP_NAME: Lab1DemoTodoList
  AZURE_RESOURCE_GROUP: CloudLab
  DOCKER_COMPOSE_FILE: lab/lab1
  DOCKER_COMPOSE_WEBAPP_FILE: lab/lab1/devops
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  ACR_NAME: acrcouldresgistry
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "adopt"

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('lab/lab1/todo-list-server/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Build Backend
        run: mvn clean package -f lab/lab1/todo-list-server/pom.xml

      - name: Set up Docker Compose
        run: docker-compose -f lab/lab1/docker-compose.yml build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: | 
          cd lab/lab1
          docker-compose -f docker-compose.yml up -d

      - name: Build and push
        run: |
          cd lab/lab1
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
          
#   pull-images:
#     needs: [build]
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Authenticate Docker to Docker Hub
#         run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Pull Docker Compose images
#         run: |
#           cd $DOCKER_COMPOSE_FILE
#           docker-compose pull

#       - name: Check Pulled Docker Images
#         run: docker images

# #       - name: Pull Docker Images from Docker Hub
# #         run: |
# #           docker pull flamesunrise/lab1_frontend:v1
# #           docker pull flamesunrise/lab1_backend:v1
# #           docker pull flamesunrise/lab1_database:v1

  before-deploy:
#     needs: [build, pull-images]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}


  # deploy-frontend:
  #   needs: [before-deploy]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  #     - name: Azure App Service frontend
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: Lab1DemoTodoList
  #         images: |
  #           docker.io/flamesunrise/lab1_frontend:v1

  deploy-backend:
    needs: [before-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure App Service backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: lab-todo-backend
          images: |
            docker.io/flamesunrise/lab1_backend:v1
        
#       - name: Deploy Docker Images to Azure Web App
#         run: |
#           az webapp config container set \
#             --name $AZURE_WEBAPP_NAME \
#             --resource-group $AZURE_RESOURCE_GROUP \
#             --docker-custom-image-name flamesunrise/lab1_database:v1 \
#             --docker-registry-server-url https://index.docker.io/v1/ \
#             --docker-registry-server-user ${{ secrets.DOCKERHUB_USERNAME }} \
#             --docker-registry-server-password ${{ secrets.DOCKERHUB_PASSWORD }}
#           az webapp config container set \
#             --name $AZURE_WEBAPP_NAME \
#             --resource-group $AZURE_RESOURCE_GROUP \
#             --docker-custom-image-name flamesunrise/lab1_backend:v1 \
#             --docker-registry-server-url https://index.docker.io/v1/ \
#             --docker-registry-server-user ${{ secrets.DOCKERHUB_USERNAME }} \
#             --docker-registry-server-password ${{ secrets.DOCKERHUB_PASSWORD }}
#           az webapp config container set \
#             --name $AZURE_WEBAPP_NAME \
#             --resource-group $AZURE_RESOURCE_GROUP \
#             --docker-custom-image-name flamesunrise/lab1_frontend:v1 \
#             --docker-registry-server-url https://index.docker.io/v1/ \
#             --docker-registry-server-user ${{ secrets.DOCKERHUB_USERNAME }} \
#             --docker-registry-server-password ${{ secrets.DOCKERHUB_PASSWORD }}


